Create Interoperability Precis.md
open-voice-network/docs pull request #267
Opened 2021-10-01 23:31 UTC by jcstine

2021-10-03 16:10 UTC, pmotch requested changes
Lots of markdown fixes needed. You can always click the "preview" tab to make sure it renders as you prefer. There are also a lot of great Markdown editors you can use to do live editing as well; something to consider.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +● Conversational platform: the combination of components that enables the operation and management of one or more conversational agents. These components may include artificial intelligence-powered n
There's a typo at the end of the sentence. A `4` after "others".

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +The lack of interoperability between market-leading, proprietary conversational agents requires that organizational users of voice must develop and maintain multiple, proprietary systems, or invest i
Typo: `inquiry5found`

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +The lack of interoperability between market-leading, proprietary conversational agents requires that organizational users of voice must develop and maintain multiple, proprietary systems, or invest i
Also, banal, but we say `IOT` above, then here we say `Internet of Things (IOT)`. The latter should probably come first, then "IOT" can be used as an abbreviation from there on out.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +The benefits of agent-to-agent interoperability:
Several sub-bullets appear to need a new line in many of the main bullets in this section.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +● Make itself available to meet a user request on behalf of another trusted voice agent ● Support security and privacy by design.
Another new line needed.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +● protocols consisting of sequences of messages that implement the enhancement; and, ● a set of self-defined data formats for transferring data among agents.
New line needed

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +Other possible enhancements include:
Without an extra return here, this line will appear in line with the previous paragraph.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +These and other potential enhancements are currently outside of the scope of the Open Voice Network Voice Agent Interoperability initiative.
Probably want a new line before this sentence. Will appear in the previous bullet.

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +○ Review and contribute to the work as your schedule permits. Documents (including this one) can be found in the Open Voice Network GitHub repository. Should you see a reason for revision, simply ope
A proper way to say it: "...can be found in the Open Voice Network GitHub organization in the docs repository"

2021-10-03 16:10 UTC, pmotch commented on folderAWG/Interoperability Precis.md
> +● Raise your voice on behalf of the Open Voice Network interoperability initiative: ○ Join the Open Voice Network Ambassador corps. OVON Ambassadors participate regularly in public forums, whether th
Other sub-bullets needed newlines in this line and the line after.

2021-10-03 16:12 UTC, pmotch commented
Also noticed its in a folder called `folderAWG`; unsure if that's on purpose or not. Also, did you mean to call the filename "Create Interoperability Precis.md". Just checking in case.

2022-01-13 14:58 UTC, JohnTrammellTarget commented
@jcstine is the work in this PR superseded by the other précis work done elsewhere?

2022-02-09 21:53 UTC, JohnTrammellTarget commented
Will be resubmitting as PDF

2022-02-09 21:53 UTC, closed without merging